### ISSUE TITLE
Android app crash when reloading events

### ISSUE THREAD

**Issue by Elektordi** [alfio-event/Alf.ioBackoffice#51]
I'm using a test account on demo.alf.io to confirm the bug is not linked to my server.
I'm also using the latest version of the app on the store.
Device is a Pixel 4a on up-to-date Android 13.

When on the events list, if I pull down to trigger a reload, the app crashes.

Here are the logs:

```03-18 14:42:02.895 23478 23478 D AndroidRuntime: Shutting down VM
03-18 14:42:02.896 23478 23478 E AndroidRuntime: FATAL EXCEPTION: main
03-18 14:42:02.896 23478 23478 E AndroidRuntime: Process: alfio.scan, PID: 23478
03-18 14:42:02.896 23478 23478 E AndroidRuntime: java.lang.NullPointerException: Attempt to read from field 'int android.view.View.mViewFlags' on a null object reference in method 'void android.view.ViewGroup.dispatchDraw(android.graphics.Canvas)'
03-18 14:42:02.896 23478 23478 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4289)
03-18 14:42:02.896 23478 23478 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:22059)
03-18 14:42:02.896 23478 23478 E AndroidRuntime: 	at android.view.View.draw(View.java:22932)
03-18 14:42:02.896 23478 23478 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
03-18 14:42:02.896 23478 23478 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
03-18 14:42:02.896 23478 23478 E AndroidRuntime: 	at android.view.View.draw(View.java:23204)
03-18 14:42:02.896 23478 23478 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:22068)
03-18 14:42:02.896 23478 23478 E AndroidRuntime: 	at android.view.View.draw(View.java:22932)
03-18 14:42:02.896 23478 23478 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
03-18 14:42:02.896 23478 23478 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
03-18 14:42:02.896 23478 23478 E AndroidRuntime: 	at android.view.View.draw(View.java:23204)
03-18 14:42:02.896 23478 23478 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:22068)
03-18 14:42:02.896 23478 23478 E AndroidRuntime: 	at android.view.View.draw(View.java:22932)
03-18 14:42:02.896 23478 23478 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
03-18 14:42:02.896 23478 23478 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
03-18 14:42:02.896 23478 23478 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:22059)
03-18 14:42:02.896 23478 23478 E AndroidRuntime: 	at android.view.View.draw(View.java:22932)
03-18 14:42:02.896 23478 23478 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
03-18 14:42:02.896 23478 23478 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
03-18 14:42:02.896 23478 23478 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:22059)
03-18 14:42:02.896 23478 23478 E AndroidRuntime: 	at android.view.View.draw(View.java:22932)
03-18 14:42:02.896 23478 23478 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
03-18 14:42:02.896 23478 23478 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
03-18 14:42:02.896 23478 23478 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:22059)
03-18 14:42:02.896 23478 23478 E AndroidRuntime: 	at android.view.View.draw(View.java:22932)
03-18 14:42:02.896 23478 23478 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
03-18 14:42:02.896 23478 23478 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
03-18 14:42:02.896 23478 23478 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:22059)
03-18 14:42:02.896 23478 23478 E AndroidRuntime: 	at android.view.View.draw(View.java:22932)
03-18 14:42:02.896 23478 23478 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
03-18 14:42:02.896 23478 23478 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
03-18 14:42:02.896 23478 23478 E AndroidRuntime: 	at android.view.View.draw(View.java:23204)
03-18 14:42:02.896 23478 23478 E AndroidRuntime: 	at com.android.internal.policy.DecorView.draw(DecorView.java:821)
03-18 14:42:02.896 23478 23478 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:22068)
03-18 14:42:02.896 23478 23478 E AndroidRuntime: 	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:689)
03-18 14:42:02.896 23478 23478 E AndroidRuntime: 	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:695)
03-18 14:42:02.896 23478 23478 E AndroidRuntime: 	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:793)
03-18 14:42:02.896 23478 23478 E AndroidRuntime: 	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4670)
03-18 14:42:02.896 23478 23478 E AndroidRuntime: 	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4381)
03-18 14:42:02.896 23478 23478 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3600)
03-18 14:42:02.896 23478 23478 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2328)
03-18 14:42:02.896 23478 23478 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9080)
03-18 14:42:02.896 23478 23478 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1231)
03-18 14:42:02.896 23478 23478 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
03-18 14:42:02.896 23478 23478 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:899)
03-18 14:42:02.896 23478 23478 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:832)
03-18 14:42:02.896 23478 23478 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
03-18 14:42:02.896 23478 23478 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:942)
03-18 14:42:02.896 23478 23478 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
03-18 14:42:02.896 23478 23478 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
03-18 14:42:02.896 23478 23478 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
03-18 14:42:02.896 23478 23478 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7872)
03-18 14:42:02.896 23478 23478 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-18 14:42:02.896 23478 23478 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
03-18 14:42:02.896 23478 23478 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
03-18 14:42:02.905  2040 16967 W ActivityTaskManager:   Force finishing activity alfio.scan/com.tns.NativeScriptActivity
03-18 14:42:02.927  2040  2138 I ActivityManager: Showing crash dialog for package alfio.scan u0
```

**Comment by cbellone** [comment]
new version (1.6.0) is being released. Thanks for reporting this 👍
